package slack

import (
	"context"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"time"

	"github.com/itsHabib/huddle/internal/types"

	slackapi "github.com/slack-go/slack"
)

func (a *slackGoAdapter) PostMessage(ctx context.Context, channelID, text, threadTS string) (string, error) {
	opts := []slackapi.MsgOption{
		slackapi.MsgOptionText(text, false),
	}
	if strings.TrimSpace(threadTS) != "" {
		opts = append(opts, slackapi.MsgOptionTS(threadTS))
	}

	_, ts, err := a.client.PostMessageContext(ctx, channelID, opts...)
	if err != nil {
		return "", fmt.Errorf("post message to channel %s: %w", channelID, err)
	}

	return ts, nil
}

// historyMinLimit / historyDefaultLimit / historyMaxLimit are the bounds the
// Slack conversations.history API accepts. limit <= 0 errors out; > 999 is
// silently capped by the API. Clamp here so handler-stream callers can pass
// raw values from ReadArgs without leaking surface-level errors.
const (
	historyDefaultLimit = 100
	historyMaxLimit     = 999
)

func (a *slackGoAdapter) History(ctx context.Context, channelID string, since *time.Time, limit int) ([]types.Message, error) {
	switch {
	case limit <= 0:
		limit = historyDefaultLimit
	case limit > historyMaxLimit:
		limit = historyMaxLimit
	}

	params := &slackapi.GetConversationHistoryParameters{
		ChannelID: channelID,
		Limit:     limit,
	}

	if since != nil && !since.IsZero() {
		ts := strconv.FormatFloat(float64(since.UTC().UnixNano())/1e9, 'f', 6, 64)
		params.Oldest = ts
	}

	resp, err := a.client.GetConversationHistoryContext(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("fetch history channel %s: %w", channelID, err)
	}

	msgs, err := a.mapConversationMessages(ctx, resp.Messages)

	return msgs, err
}

// systemSubTypes lists the Slack message subtypes generated by the system
// (channel state changes, app installs, etc.) — these aren't user content
// and shouldn't appear in huddle history. Everything else (including
// thread_broadcast, me_message, file_share, bot_message, message_replied)
// is legitimate content posted by users or apps.
func isSystemHistorySubType(subType string) bool {
	_, ok := systemSubTypes[strings.TrimSpace(subType)]

	return ok
}

var systemSubTypes = map[string]struct{}{
	"channel_join":      {},
	"channel_leave":     {},
	"channel_topic":     {},
	"channel_purpose":   {},
	"channel_name":      {},
	"channel_archive":   {},
	"channel_unarchive": {},
	"group_join":        {},
	"group_leave":       {},
	"pinned_item":       {},
	"unpinned_item":     {},
	"reminder_add":      {},
	"reminder_delete":   {},
	"tombstone":         {},
}

func (a *slackGoAdapter) mapConversationMessages(ctx context.Context, messages []slackapi.Message) ([]types.Message, error) {
	msgs := make([]types.Message, 0, len(messages))
	lookupFailed := make(map[string]struct{})

	for _, sm := range messages {
		subType := strings.TrimSpace(sm.SubType)
		if isSystemHistorySubType(subType) {
			continue
		}

		id := strings.TrimSpace(sm.Timestamp)
		if id == "" && sm.SubMessage != nil {
			id = strings.TrimSpace(sm.SubMessage.Timestamp)
		}

		txt := strings.TrimSpace(sm.Text)
		if txt == "" && sm.SubMessage != nil {
			txt = strings.TrimSpace(sm.SubMessage.Text)
		}

		posted, perr := parseSlackTSToTime(id)
		if perr != nil {
			return nil, fmt.Errorf("parse Slack ts %q: %w", id, perr)
		}

		identity, body := Decode(txt)

		rawUser := strings.TrimSpace(sm.User)
		if rawUser == "" && sm.SubMessage != nil {
			rawUser = strings.TrimSpace(sm.SubMessage.User)
		}

		if identity.Kind == types.IdentityKindHuman && rawUser != "" {
			identity = a.enrichHumanIdentity(ctx, identity, rawUser, lookupFailed)
		}

		threadTS := strings.TrimSpace(sm.ThreadTimestamp)
		if threadTS == "" && sm.SubMessage != nil {
			threadTS = strings.TrimSpace(sm.SubMessage.ThreadTimestamp)
		}

		msgs = append(msgs, types.Message{
			ID:        id,
			Body:      body,
			PostedAt:  posted,
			ThreadTS:  threadTS,
			SubType:   sm.SubType,
			Identity:  identity,
			UserIDRaw: rawUser,
		})
	}

	return msgs, nil
}

func (a *slackGoAdapter) enrichHumanIdentity(
	ctx context.Context,
	identity types.Identity,
	rawUser string,
	lookupFailed map[string]struct{},
) types.Identity {
	if a.orchestratorSlackUserID != "" && rawUser == a.orchestratorSlackUserID {
		identity.Kind = types.IdentityKindOrchestrator
	}

	if _, alreadyFailed := lookupFailed[rawUser]; alreadyFailed {
		identity.DisplayName = "user-" + rawUser

		return identity
	}

	info, err := a.LookupUser(ctx, rawUser)
	if err == nil && info.DisplayName != "" {
		identity.DisplayName = info.DisplayName

		return identity
	}

	lookupFailed[rawUser] = struct{}{}
	identity.DisplayName = "user-" + rawUser
	if err != nil {
		slog.WarnContext(ctx, "users.info lookup failed for message author; using synthetic display name",
			"slack_user_id", rawUser,
			"err", err,
		)
	}

	return identity
}

func parseSlackTSToTime(tsStr string) (time.Time, error) {
	if strings.TrimSpace(tsStr) == "" {
		return time.Time{}, nil
	}

	f, err := strconv.ParseFloat(tsStr, 64)
	if err != nil {
		return time.Time{}, err
	}

	sec := int64(f)
	sub := f - float64(sec)

	nsec := int64(sub * 1e9)

	return time.Unix(sec, nsec).UTC(), nil
}
